eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
jwt:
  config:
    key: itcast
server:
  port: 9001
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: ''
    url: jdbc:mysql://127.0.0.1:3306/tensquare_base?characterEncoding=utf-8
    username: root
  jpa:
    database: mysql
    show-sql: true
