eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
jwt:
  config:
    key: itcast
server:
  port: 9001
spring:
  application:
    name: tensquare-user
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/tensquare_user?characterEncoding=UTF8
    username: root
  jpa:
    database: mysql
    show-sql: true
