server:
  port: 9007
spring:
  application:
    name: tensquare-search
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
  rabbitmq:
    host: 127.0.0.1  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true
jwt:
  config:
    key: itcast
